### ISSUE TITLE
bug:okhttp3引用后调用报错

### ISSUE THREAD

**Issue by gang0713** [justauth/JustAuth#145]
使用okhttps-3.4.2 +okhttp-3.14.9和4.9.3都报一样的错误

Caused by: java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;
at com.xkcoding.http.support.okhttp3.OkHttp3Impl.post(OkHttp3Impl.java:177)
at com.xkcoding.http.support.okhttp3.OkHttp3Impl.post(OkHttp3Impl.java:161)
at com.xkcoding.http.support.okhttp3.OkHttp3Impl.post(OkHttp3Impl.java:149)
at com.xkcoding.http.HttpUtil.post(HttpUtil.java:141)
at me.zhyd.oauth.utils.HttpUtils.post(HttpUtils.java:55)
at me.zhyd.oauth.request.AuthDouyinRequest.getToken(AuthDouyinRequest.java:90)
at me.zhyd.oauth.request.AuthDouyinRequest.getAccessToken(AuthDouyinRequest.java:38)
at me.zhyd.oauth.request.AuthDefaultRequest.login(AuthDefaultRequest.java:80)
at com.ruoyi.web.controller.system.SysAuthController.login(SysAuthController.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)

**Comment by wmhxx** [comment]
![image](https://user-images.githubusercontent.com/58652226/204517548-86ba4668-d014-45f3-a074-3238081ec80a.png)
这样试试
